### ISSUE TITLE
What license is applied to this repository?

### ISSUE THREAD

**Issue by kamotsuru** [jpf/sms-via-email#5]
This is not a issue.

I'd like to publish the modified code of this repository also to github. The main modification is to be python3 compliant and Vonage API support.
However, this repository doesn't show any license, e.g. GNU, Apache, MIT, .... Then, could you let me know what license is applied?

Thanks in advance.

**Comment by jpf** [comment]
I license this under MIT. If you send a PR, please include the license!

**Comment by kamotsuru** [comment]
Thanks!
